"""
Exports for the S&P 500 vs. gold brief: markdown, Excel (live-sourced
values in blue with derived cells as real formulas), Word, and PDF —
via the suite's existing export layer. Every artifact opens with the
analysis-not-advice stamp and closes with the data-gaps list.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from openpyxl import Workbook  # noqa: E402

from shared.excel_utils import (  # noqa: E402
    BLUE, FMT_PCT, GRAY, HDR_FILL, HDR_FONT, set_cell, set_widths,
    sheet_title,
)
from shared.exports.docx_memo import Memo  # noqa: E402
from shared.exports.pdf import to_pdf  # noqa: E402

DISCLAIMER = ("AI-assisted comparative analysis to inform thinking — not a "
              "recommendation, not financial advice. Markets can move "
              "against sound reasoning in the short run. Every figure is "
              "dated and sourced; gaps are stated, not papered over.")


def render_markdown(brief) -> str:
    v = brief["view"]
    lines = [
        f"# S&P 500 vs. Gold — Comparative Brief ({brief['as_of']})",
        f"\n> {DISCLAIMER}\n",
        "## Snapshot",
        "| Metric | S&P 500 | Gold | As of | Source |", "|---|---|---|---|---|",
        *[f"| {r['metric']} | {r['spx']} | {r['gold']} | {r['as_of']} "
          f"| {r['source']} |" for r in brief["rows"]],
        "\n## Macro backdrop", *[p + "\n" for p in brief["macro"]],
        "## The case for the S&P 500 right now",
        *[f"- {b}" for b in v["case_spx"]],
        "\n## The case for gold right now",
        *[f"- {b}" for b in v["case_gold"]],
        f"\n## AI Summary & Reasoned View — lean: **{v['lean']}**",
        f"*(Generated by {brief['model']} from the retrieved facts pack "
        "above — weigh it as one input, not the decision.)*\n",
        v["reasoned_view"],
        "\n### What would change this view",
        *[f"- {x}" for x in v["what_would_change"]],
    ]
    gaps = brief["research"]["gaps"]
    if gaps:
        lines.append(f"\n### Data gaps this run\n{', '.join(gaps)} — no "
                     "sourced figure found; the view above was instructed "
                     "not to lean on these.")
    return "\n".join(lines)


def build_xlsx(brief, path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Snapshot"
    sheet_title(ws, f"S&P 500 vs. Gold — {brief['as_of']}", DISCLAIMER)
    for j, h in enumerate(("Metric", "S&P 500", "Gold", "As of", "Source")):
        set_cell(ws, f"{chr(65 + j)}4", h, HDR_FONT, fill=HDR_FILL)
    for i, r in enumerate(brief["rows"], start=5):
        set_cell(ws, f"A{i}", r["metric"])
        set_cell(ws, f"B{i}", r["spx"], BLUE)
        set_cell(ws, f"C{i}", r["gold"], BLUE)
        set_cell(ws, f"D{i}", str(r["as_of"]), GRAY)
        set_cell(ws, f"E{i}", r["source"], GRAY)
    set_widths(ws, {"A": 34, "B": 22, "C": 30, "D": 12, "E": 44})

    # Live-formula sheet: raw sourced inputs blue, derived cells are REAL
    # formulas per the suite convention.
    d = wb.create_sheet("Data")
    sheet_title(d, "Live data & derived metrics",
                "Blue = sourced input (dated). Black = formula — edit an "
                "input and the derived values recalculate.")
    data, der = brief["data"], brief["der"]
    ret = data["returns"]
    rows = [
        ("S&P 500 level (^GSPC)", data["spx"]["price"], data["as_of"]),
        ("S&P proxy price — current (SPY)", ret["spx"]["current"]["price"],
         ret["spx"]["current"]["date"]),
        ("S&P proxy — prior year end", ret["spx"]["anchors"]["ytd"]["price"],
         ret["spx"]["anchors"]["ytd"]["date"]),
        ("S&P proxy — 1yr ago", ret["spx"]["anchors"]["1y"]["price"],
         ret["spx"]["anchors"]["1y"]["date"]),
        ("S&P proxy — 5yr ago", ret["spx"]["anchors"]["5y"]["price"],
         ret["spx"]["anchors"]["5y"]["date"]),
        ("Gold spot — current", ret["gold"]["current"]["price"],
         ret["gold"]["current"]["date"]),
        ("Gold — prior year end", ret["gold"]["anchors"]["ytd"]["price"],
         ret["gold"]["anchors"]["ytd"]["date"]),
        ("Gold — 1yr ago", ret["gold"]["anchors"]["1y"]["price"],
         ret["gold"]["anchors"]["1y"]["date"]),
        ("Gold — 5yr ago", ret["gold"]["anchors"]["5y"]["price"],
         ret["gold"]["anchors"]["5y"]["date"]),
        ("10Y treasury (%)", der["ten_y"], data["macro"]["as_of"]),
        ("CPI YoY (%)", der["inflation"],
         data["macro"]["indicators"].get("inflationRate", {}).get("date")),
        ("S&P trailing P/E (web-sourced)",
         brief["research"]["spx_trailing_pe"]["value"],
         brief["research"]["spx_trailing_pe"].get("as_of")),
    ]
    for i, (label, val, as_of) in enumerate(rows, start=5):
        set_cell(d, f"A{i}", label)
        if val is not None:
            set_cell(d, f"B{i}", round(float(val), 4), BLUE)
        else:
            set_cell(d, f"B{i}", "not obtained this run", GRAY)
        set_cell(d, f"C{i}", str(as_of or ""), GRAY)

    set_cell(d, "A18", "Derived (live formulas)", None, bold=True)
    derived = [
        ("S&P YTD return", "=B6/B7-1", FMT_PCT, True),
        ("S&P 1-yr return", "=B6/B8-1", FMT_PCT, True),
        ("S&P 5-yr return", "=B6/B9-1", FMT_PCT, True),
        ("Gold YTD return", "=B10/B11-1", FMT_PCT, True),
        ("Gold 1-yr return", "=B10/B12-1", FMT_PCT, True),
        ("Gold 5-yr return", "=B10/B13-1", FMT_PCT, True),
        ("Real yield approx (10Y − CPI YoY, pp)", "=B14-B15", "0.00", True),
        ("Earnings yield (%)", "=100/B16", "0.00",
         brief["research"]["spx_trailing_pe"]["value"] is not None),
        ("ERP proxy (EY − 10Y, pp)", "=100/B16-B14", "0.00",
         brief["research"]["spx_trailing_pe"]["value"] is not None),
    ]
    for i, (label, formula, fmt, available) in enumerate(derived, start=19):
        set_cell(d, f"A{i}", label)
        if available:
            set_cell(d, f"B{i}", formula, None, fmt)
        else:
            set_cell(d, f"B{i}", "needs trailing P/E (not obtained)", GRAY)
    set_widths(d, {"A": 40, "B": 22, "C": 14})
    wb.save(path)
    return path


def build_outputs(brief, outdir=".") -> dict:
    outdir = Path(outdir)
    stem = f"sp500_vs_gold_{brief['as_of']}"
    md_path = outdir / f"{stem}.md"
    md_path.write_text(render_markdown(brief))
    xlsx_path = build_xlsx(brief, outdir / f"{stem}.xlsx")

    v = brief["view"]
    memo = Memo(f"S&P 500 vs. Gold — Comparative Brief",
                f"As of {brief['as_of']} | {DISCLAIMER}")
    memo.heading("Snapshot")
    memo.table([["Metric", "S&P 500", "Gold", "As of", "Source"]]
               + [[r["metric"], r["spx"], r["gold"], str(r["as_of"]),
                   r["source"]] for r in brief["rows"]])
    memo.heading("Macro backdrop")
    for p in brief["macro"]:
        memo.para(p)
    memo.heading("The case for the S&P 500 right now")
    memo.bullets(v["case_spx"])
    memo.heading("The case for gold right now")
    memo.bullets(v["case_gold"])
    memo.heading(f"AI Summary & Reasoned View — lean: {v['lean']}")
    memo.para(f"Generated by {brief['model']} from the retrieved facts "
              "pack; one input into a decision, not the decision.",
              small=True)
    memo.para(v["reasoned_view"])
    memo.heading("What would change this view", level=2)
    memo.bullets(v["what_would_change"])
    if brief["research"]["gaps"]:
        memo.heading("Data gaps this run", level=2)
        memo.para(", ".join(brief["research"]["gaps"]) + " — no sourced "
                  "figure found; the view was instructed not to lean on "
                  "these.", small=True)
    docx_path = memo.save(outdir / f"{stem}.docx")
    pdf_path = to_pdf(docx_path, outdir)
    return dict(md=md_path, xlsx=xlsx_path, docx=docx_path, pdf=pdf_path)
